import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { artistasDeBases } from '../src/js/util/seguir-artistas.js';
let n = 0;
const eq = (actual, expected, msg) => { n++; assert.deepEqual(actual, expected, msg); };
const source = readFileSync(new URL('../src/js/api.js', import.meta.url), 'utf8');
const block = source.slice(source.indexOf('const LIBRARY_URIS_POR_REQUEST ='), source.indexOf('async function checkLibraryContains')).replace(/\bexport /g, '');
const factory = new Function('spotifyFetch', block + '\nreturn {consultarSeguimientoArtistas,seguirArtistas};');
const ids = Array.from({length:351}, (_, i) => String(i).padStart(22, '0'));
let calls = [];
const api = factory(async (url, opts) => {
  const uris = new URL(url, 'https://api.spotify.com').searchParams.get('uris').split(',');
  calls.push({url,opts,uris});
  return uris.map((_, i) => i % 2 === 0);
});
const states = await api.consultarSeguimientoArtistas(ids);
eq(calls.length, 9, '351 requieren nueve peticiones');
eq(calls.map(c=>c.uris.length), [40,40,40,40,40,40,40,40,31], 'fronteras del lote');
eq(states.size, 351, 'todos tienen estado');
eq(calls.every(c=>c.url.startsWith('/me/library/contains?') && c.uris.every(u=>u.startsWith('spotify:artist:'))), true, 'rutas y URIs vigentes');
eq(calls.every(c=>c.opts._maxRetries===0), true, 'no reintenta cuota en silencio');
calls=[];
await api.seguirArtistas([ids[0],ids[1],ids[0]]);
eq(calls.length,1,'un PUT para una selección pequeña');
eq(calls[0].opts.method,'PUT','escritura explícita');
eq(calls[0].uris.length,2,'deduplica');
calls=[];
await api.seguirArtistas(ids.slice(0,41));
eq(calls.map(c=>c.uris.length),[40,1],'41 se divide en dos PUT');
calls=[];
await api.consultarSeguimientoArtistas([]); await api.seguirArtistas([]);
eq(calls.length,0,'sin selección no hay red');
await assert.rejects(()=>api.seguirArtistas(['id-invalido'])); n++;
eq(calls.length,0,'rechaza id inválido antes de red');
for(const respuesta of [[],[false],Array(40).fill(null),Array(40).fill(1)]) {
 let batches=0;
 await assert.rejects(()=>factory(async()=>respuesta).consultarSeguimientoArtistas(ids.slice(0,40),{onBatch:()=>batches++}));n++;
 eq(batches,0,'respuesta inválida nunca significa no seguido');
}
let batches=[], count=0;
const fail = factory(async()=>{ if(++count===2) throw new Error('429'); return []; });
const partial=await fail.seguirArtistas(ids.slice(0,90),{onBatch:ids=>batches.push(ids)});
eq(partial.seguidos.length,40,'conserva primer lote confirmado');
eq(partial.pendientes.length,50,'no pierde el resto');
eq(count,2,'se corta al primer error');
eq(batches.length,1,'solo comunica éxitos');
eq(partial.error.message,'429','no tapa error');
let readBatches=[]; count=0;
const failRead=factory(async()=>{if(++count===2)throw new Error('red');return Array(40).fill(true);});
await assert.rejects(()=>failRead.consultarSeguimientoArtistas(ids.slice(0,90),{onBatch:b=>readBatches.push(b)}));n++;
eq(readBatches[0].size,40,'lectura parcial conservable');
eq(count,2,'no continúa tras fallo');
const entries=[0,1,2].map(i=>['discover_disco_base_v1_'+ids[i],{value:{items:[{artists:[{id:ids[i],name:'Artista '+i}]}]}}]);
const likes=[{track:{id:'t',artists:[{id:ids[1],name:'B'},{id:ids[2],name:'C'}]}},{track:{id:'t',artists:[{id:ids[1],name:'B'}]}},{track:{id:'u',artists:[{id:ids[2],name:'C'}]}}];
const result=artistasDeBases(entries,likes);
eq(result.map(a=>a.id),[ids[2],ids[1],ids[0]],'ordena por likes únicos por artista');
eq(result.map(a=>a.likes),[2,1,0],'incluye colaboradores y no duplica pista');
eq(result[2].name,'Artista 0','nombre desde base sin red');
eq(artistasDeBases([],likes),[],'no agrega artistas fuera de las bases');
console.log(`${n} asserts OK`);
